# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Leonardo Silva
email: kakuzops@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Meu nome é Leonardo da Silva Nogueira, nascido e criado em São Paulo a famosa selva de pedra
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kakuzops.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kakuzops
github_username:  kakuzops


date_format: "%b %d, %y"


twitter: kakuzops
#  username:
instagram_username: kakuzoPs

linkedin_username: leonardo-silva-94aa7998/

#  site:


# gitlab on site
gitlab:
  owner_url: https://gitlab.com/leonard9

# github on site
github:
  owner_url: https://github.com/leonard9


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

